version: '3.8'

services:

  db:
    image: mariadb:11.0.2
    restart: always
    ports:
      - "${dport}:3306"
    volumes:
      - nnew-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "${wport}:80"
    depends_on:
      - db
    volumes:
      - nnew-data:/var/www/html
    environment:

      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

      WORDPRESS_CONFIG_EXTRA: |

        /** disable wp core auto update */
        define('WP_AUTO_UPDATE_CORE', false);


volumes:
    nnew-data:
    nnew-db:
